<?php declare(strict_types=1);

namespace App\Enums;

use BenSampo\Enum\Enum;

/**
 * @method static static OptionOne()
 * @method static static OptionTwo()
 * @method static static OptionThree()
 */
final class DokuEnum extends Enum
{
    const SERVICE_VIRTUAL_ACCOUNT = "VIRTUAL_ACCOUNT";
    const SERVICE_ONLINE_TO_OFFLINE = "ONLINE_TO_OFFLINE";
    const SERVICE_EMONEY = "EMONEY";
    const SERVICE_CREDIT_CARD = "CREDIT_CARD";
    const SERVICE_MANUAL_PAYMENT = "MANUAL_PAYMENT";

    const CHANNEL_VIRTUAL_ACCOUNT_BRI = "VIRTUAL_ACCOUNT_BRI";
    const CHANNEL_VIRTUAL_ACCOUNT_BANK_SYARIAH_MANDIRI = "VIRTUAL_ACCOUNT_BANK_SYARIAH_MANDIRI";
    const CHANNEL_VIRTUAL_ACCOUNT_BANK_MANDIRI = "VIRTUAL_ACCOUNT_BANK_MANDIRI";
    const CHANNEL_VIRTUAL_ACCOUNT_BCA = "VIRTUAL_ACCOUNT_BCA";
    const CHANNEL_VIRTUAL_ACCOUNT_BNI = "VIRTUAL_ACCOUNT_BNI";
    const CHANNEL_VIRTUAL_ACCOUNT_BANK_DANAMON = "VIRTUAL_ACCOUNT_BANK_DANAMON";
    const CHANNEL_VIRTUAL_ACCOUNT_BANK_PERMATA = "VIRTUAL_ACCOUNT_BANK_PERMATA";
    const CHANNEL_VIRTUAL_ACCOUNT_BANK_CIMB = "VIRTUAL_ACCOUNT_BANK_CIMB";
    const CHANNEL_VIRTUAL_ACCOUNT_DOKU = "VIRTUAL_ACCOUNT_DOKU";

    const CHANNEL_ONLINE_TO_OFFLINE_ALFA = "ONLINE_TO_OFFLINE_ALFA";
    const CHANNEL_ONLINE_TO_OFFLINE_INDOMARET = "ONLINE_TO_OFFLINE_INDOMARET";

    const CHANNEL_EMONEY_OVO = "EMONEY_OVO";
    const CHANNEL_EMONEY_SHOPEEPAY = "EMONEY_SHOPEE_PAY";
    const CHANNEL_EMONEY_DOKU = "EMONEY_DOKU";

    const CHANNEL_DIRECT_DEBIT_BRI = "DIRECT_DEBIT_BRI";

    const CHANNEL_PEER_TO_PEER_AKULAKU = "PEER_TO_PEER_AKULAKU";
    const CHANNEL_PEER_TO_PEER_KREDIVO = "PEER_TO_PEER_KREDIVO";
    const CHANNEL_PEER_TO_PEER_INDODANA = "PEER_TO_PEER_INDODANA";

    const CHANNEL_QRIS = "QRIS";

    const CHANNEL_CREDIT_CARD = "CREDIT_CARD";


}
